"""Numeric non-regression fixture — developmental curve transfer values.

Purpose
-------
The directional tests in ``test_developmental_curve.py`` assert ordinal
properties (CE1→CE2 transfer > CP→CE1 transfer, etc.) but they do NOT pin
the actual numeric values.  A change to a skill-weight, bank size, or mastery
threshold could shift every transfer number while preserving the ordering —
and the existing tests would pass silently.

This test pins the **exact computed values** of the developmental curve as they
are produced by the current code with the fixed seed (SEED = 7 inside
``scripts/developmental.py``).  Any future change that shifts a numeric value
will fail here first, prompting a deliberate decision: either the change is
intentional (update the fixture consciously after review) or it is a silent
regression (fix the code).

NO RESULTS ARE ASSERTED EXCEPT WHAT THE CODE ACTUALLY COMPUTES.
This file was generated by running ``scripts/developmental_curve.py`` once and
recording its output.  The fixture is a lock, not a claim about absolute values.

Anti-illusion note: nothing here adds to the scientific claim. The *science*
is in ``test_developmental_curve.py`` and ``test_developmental_evidence.py``
(the directional/structural findings). This file protects the *reproducibility*
of those findings against silent code drift.

DO NOT MODIFY the expected values without running the full curve script and
understanding why the output changed.
"""
from __future__ import annotations

import importlib.util
import os
import tempfile

import pytest

# Load the developmental_curve script via importlib (same pattern used in
# test_developmental_curve.py — keeps the test self-contained and does not
# import the module as a package).
_SPEC = importlib.util.spec_from_file_location(
    "developmental_curve",
    os.path.join(os.path.dirname(__file__), "..", "scripts", "developmental_curve.py"),
)
_curve_mod = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_curve_mod)


@pytest.fixture(scope="module")
def curve(tmp_path_factory):
    """Run the developmental curve once per test-session (expensive but cached)."""
    out = tmp_path_factory.mktemp("curve_numeric")
    rep = tmp_path_factory.mktemp("curve_numeric_rep")
    return _curve_mod.run(str(out), str(rep))


# ---------------------------------------------------------------------------
# 1) Rng.fork determinism — the sha256 child seed must be stable
# ---------------------------------------------------------------------------

def test_rng_fork_seed_is_stable():
    """Rng.fork uses sha256, NOT Python's salted hash.  The child seed value
    must be identical across Python processes (PYTHONHASHSEED-independent)."""
    from sevo.rng import Rng
    # These expected values were produced by running the code once.  They must
    # never change unless Rng.fork's sha256 logic is intentionally altered.
    assert Rng(7).fork("test_tag").seed == 2241046562
    assert Rng(7).fork("math.CE1.add_within_100_carry").seed == 964335497
    assert Rng(0).fork("a").seed != Rng(0).fork("b").seed  # distinct tags -> distinct children
    assert Rng(7).fork("x").seed != Rng(42).fork("x").seed  # distinct parents -> distinct children


def test_rng_fork_draws_are_stable():
    """Five draws from a specific fork are pinned — catching any shift in the
    internal random stream (e.g. if the seed range or algorithm changes)."""
    from sevo.rng import Rng
    rng = Rng(7).fork("math.CP.add_within_20")
    draws = [rng.random() for _ in range(5)]
    expected = [
        0.7121953944325793,
        0.8014542523624621,
        0.829191494263112,
        0.7386514318641642,
        0.6310513162643097,
    ]
    assert draws == expected, f"Rng draw stream shifted: got {draws}"


# ---------------------------------------------------------------------------
# 2) Spotlight transfer values — pinned per step
#
# "spotlight" = the key arithmetic node for each transition (the bottleneck
# node): math.CE1.add_within_100_carry, math.CE2.add_within_1000,
# math.CM1.multiply_table.
# ---------------------------------------------------------------------------

def test_cp_to_ce1_spotlight_transfer_is_pinned(curve):
    """The carry bottleneck gives 0.00 transfer at CP→CE1 (carry not yet learned)."""
    s = curve["steps"]["CP->CE1"]["spotlight"]
    assert s["node"] == "math.CE1.add_within_100_carry"
    assert s["transfer"] == 0.0, f"CP->CE1 spotlight transfer changed: {s['transfer']}"
    assert s["trials_dev"] == 16,   f"CP->CE1 trials_dev changed: {s['trials_dev']}"
    assert s["trials_naive"] == 24, f"CP->CE1 trials_naive changed: {s['trials_naive']}"
    assert s["dev_pretest"] == 0.2917, f"CP->CE1 dev_pretest changed: {s['dev_pretest']}"


def test_ce1_to_ce2_spotlight_transfer_is_pinned(curve):
    """Carry is now mastered → large transfer (+0.875) at CE1→CE2."""
    s = curve["steps"]["CE1->CE2"]["spotlight"]
    assert s["node"] == "math.CE2.add_within_1000"
    assert s["transfer"] == 0.875, f"CE1->CE2 spotlight transfer changed: {s['transfer']}"
    assert s["trials_dev"] == 8,   f"CE1->CE2 trials_dev changed: {s['trials_dev']}"
    assert s["trials_naive"] == 56, f"CE1->CE2 trials_naive changed: {s['trials_naive']}"
    assert s["dev_pretest"] == 0.875, f"CE1->CE2 dev_pretest changed: {s['dev_pretest']}"
    assert s["naive_pretest"] == 0.0, f"CE1->CE2 naive_pretest changed: {s['naive_pretest']}"


def test_ce2_to_cm1_spotlight_transfer_is_pinned(curve):
    """Multiplication is a new bottleneck → 0.00 transfer at CE2→CM1."""
    s = curve["steps"]["CE2->CM1"]["spotlight"]
    assert s["node"] == "math.CM1.multiply_table"
    assert s["transfer"] == 0.0, f"CE2->CM1 spotlight transfer changed: {s['transfer']}"
    assert s["trials_dev"] == 16,   f"CE2->CM1 trials_dev changed: {s['trials_dev']}"
    assert s["trials_naive"] == 16, f"CE2->CM1 trials_naive changed: {s['trials_naive']}"


# ---------------------------------------------------------------------------
# 3) Per-node transfer map — all values pinned for CP→CE1
#
# This is the most sensitive fixture: if any bank size, skill-weight, or
# mastery threshold changes, the individual deltas shift first.
# ---------------------------------------------------------------------------

# Pinned per-node transfer deltas for the CP→CE1 step
# (developmental pretest − isolated pretest, rounded to 4 dp by the script)
_EXPECTED_CP_TO_CE1 = {
    "fr.CE1.pluriel_reguliers":        0.1818,
    "fr.CE1.pluriel_en_al":           -0.25,
    "fr.CE1.present_verbes_er":        0.0151,
    "math.CE1.add_within_100_nocarry": 0.75,
    "math.CE1.add_within_100_carry":   0.0,
    "math.CE1.sub_within_100_borrow":  0.25,
}

_EXPECTED_CE1_TO_CE2 = {
    "fr.CE2.pluriel_invariables":  0.0,
    "math.CE2.add_within_1000":    0.875,
    "math.CE2.sub_within_1000":    0.9167,
}

_EXPECTED_CE2_TO_CM1 = {
    "math.CM1.multiply_table": 0.0,
}


def test_cp_to_ce1_per_node_transfer_pinned(curve):
    """Every CE1-node delta is pinned.  A weight or bank change shifts these."""
    actual = curve["steps"]["CP->CE1"]["per_node_transfer"]
    assert set(actual) == set(_EXPECTED_CP_TO_CE1), \
        f"node set changed: added={set(actual)-set(_EXPECTED_CP_TO_CE1)}, removed={set(_EXPECTED_CP_TO_CE1)-set(actual)}"
    for node, expected_val in _EXPECTED_CP_TO_CE1.items():
        assert actual[node] == expected_val, \
            f"CP->CE1 per_node_transfer[{node}] changed: {actual[node]} != {expected_val}"


def test_ce1_to_ce2_per_node_transfer_pinned(curve):
    """CE2 nodes are pinned — in particular the arithmetic jump must be ≈ 0.875."""
    actual = curve["steps"]["CE1->CE2"]["per_node_transfer"]
    assert set(actual) == set(_EXPECTED_CE1_TO_CE2), \
        f"node set changed: {set(actual)} != {set(_EXPECTED_CE1_TO_CE2)}"
    for node, expected_val in _EXPECTED_CE1_TO_CE2.items():
        assert actual[node] == expected_val, \
            f"CE1->CE2 per_node_transfer[{node}] changed: {actual[node]} != {expected_val}"


def test_ce2_to_cm1_per_node_transfer_pinned(curve):
    """CM1 multiplication transfer stays pinned at 0.0 (new bottleneck blocks)."""
    actual = curve["steps"]["CE2->CM1"]["per_node_transfer"]
    assert set(actual) == set(_EXPECTED_CE2_TO_CM1)
    for node, expected_val in _EXPECTED_CE2_TO_CM1.items():
        assert actual[node] == expected_val, \
            f"CE2->CM1 per_node_transfer[{node}] changed: {actual[node]} != {expected_val}"


# ---------------------------------------------------------------------------
# 4) Mean-transfer values — aggregate sanity across all nodes per step
# ---------------------------------------------------------------------------

def test_mean_transfer_values_are_pinned(curve):
    """Mean transfer per step: CP→CE1 ≈ 0.1578, CE1→CE2 ≈ 0.5972, CE2→CM1 = 0.0."""
    steps = curve["steps"]
    assert steps["CP->CE1"]["mean_transfer"] == 0.1578, \
        f"CP->CE1 mean_transfer changed: {steps['CP->CE1']['mean_transfer']}"
    assert steps["CE1->CE2"]["mean_transfer"] == 0.5972, \
        f"CE1->CE2 mean_transfer changed: {steps['CE1->CE2']['mean_transfer']}"
    assert steps["CE2->CM1"]["mean_transfer"] == 0.0, \
        f"CE2->CM1 mean_transfer changed: {steps['CE2->CM1']['mean_transfer']}"


# ---------------------------------------------------------------------------
# 5) Boolean flags — structural properties of the curve
# ---------------------------------------------------------------------------

def test_curve_boolean_flags_stable(curve):
    """The top-level flags derived from the numeric comparisons must stay True."""
    assert curve["bottleneck_unlocked"] is True, \
        "bottleneck_unlocked flipped — CE1→CE2 transfer no longer exceeds CP→CE1"
    assert curve["new_bottleneck_blocks_again"] is True, \
        "new_bottleneck_blocks_again flipped — CE2→CM1 transfer no longer blocked"
